# -*- coding: utf-8 -*-
"""Generate thesis table data files (三线表) and register in assets/manifest.json.

Table content is derived from project/profile.json.
"""
import json
import os
from datetime import datetime, timezone

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ROOT = os.environ.get("THESIS_ROOT", ROOT)
TBL_DIR = os.path.join(ROOT, "assets", "tables")
os.makedirs(TBL_DIR, exist_ok=True)


# Load table config from project/tables-config.json.
# If the file does not exist, the script prints a message and exits.
# This file should be generated by the agent based on project/profile.json.
CONFIG_PATH = os.path.join(ROOT, "project", "tables-config.json")
if not os.path.exists(CONFIG_PATH):
    print(f"[skip] No tables config found at {CONFIG_PATH}")
    print("Create project/tables-config.json with a list of table definitions first.")
    print("Each entry: {id, caption, section_ref, headers, rows}")
    import sys; sys.exit(0)

TABLES = json.load(open(CONFIG_PATH, "r", encoding="utf-8"))


def main():
    mf_path = os.path.join(ROOT, "assets", "manifest.json")
    existing = []
    if os.path.exists(mf_path):
        try:
            existing = json.load(open(mf_path, "r", encoding="utf-8"))
            if not isinstance(existing, list):
                existing = []
        except Exception:
            existing = []
    existing = [a for a in existing if a.get("type") != "table"]

    registered = []
    for tbl in TABLES:
        path = os.path.join(TBL_DIR, f"{tbl['id']}.json")
        json.dump(tbl, open(path, "w", encoding="utf-8"),
                  ensure_ascii=False, indent=2)
        registered.append({
            "id": tbl["id"],
            "type": "table",
            "caption": tbl["caption"],
            "file": f"assets/tables/{tbl['id']}.json",
            "source_format": "json",
            "section_ref": tbl["section_ref"],
            "row_count": len(tbl["rows"]),
            "profile_version_at_generation": "1.0-draft",
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        })
        print(f"[ok] {tbl['id']} -> {path} ({len(tbl['rows'])} rows)")

    merged = existing + registered
    json.dump(merged, open(mf_path, "w", encoding="utf-8"),
              ensure_ascii=False, indent=2)
    print(f"[ok] manifest updated: {mf_path} ({len(merged)} assets)")


if __name__ == "__main__":
    main()
